/**
 * GENERATED FILE
 * Source: packages/kinetik-core/src/stableJson.ts
 * Generated by: npm run canonical:sync
 * DO NOT EDIT
 */

export const stableStringify = (obj: Record<string, unknown>): string => {
  const keys = Object.keys(obj).sort();
  const parts: string[] = [];
  for (const k of keys) {
    parts.push(`${JSON.stringify(k)}:${JSON.stringify(obj[k])}`);
  }
  return `{${parts.join(',')}}`;
}
