/**
 * GENERATED FILE
 *
 * Source:
 *   packages/evidence-mapping/src/index.ts
 *
 * Generated by:
 *   npm run policy:sync
 *
 * DO NOT EDIT
 */

// ============================================================================
// @getkinetik/evidence-mapping — reference policy for mapping a bureau
// attestation to a reward tier.
// ----------------------------------------------------------------------------
// Read this twice: this package is NOT THE BUREAU. The bureau ships signed
// evidence (a SignedAttestation from @getkinetik/verify) about a sovereign
// node. Mapping that evidence to a reward tier — "Should I pay this node
// the premium rate? Should I throttle them? Should I block them?" — is the
// PARTNER NETWORK'S decision, not the bureau's.
//
// This package exists so partners don't have to start from a blank file.
// It is a REFERENCE policy: the same math GETKINETIK runs on its own
// dashboard, exposed as a pure function partners can call, copy, or fork.
// If a partner runs this function against an attestation and disagrees
// with the result, they're encouraged to ship their own policy. That's
// the whole point.
//
// CONTRACT:
//   · Pure function. No clocks, no network, no state.
//   · Zero runtime dependencies. No noble, no expo, no react.
//   · Same input → same output. Versioned via POLICY_VERSION.
//
// USAGE:
//   import { attestationToTier, DEFAULT_POLICY } from '@getkinetik/evidence-mapping';
//   import { verifyArtifact } from '@getkinetik/verify';
//
//   const report = await verifyArtifact(rawAttestation);
//   if (!report.valid || report.kind !== 'attestation') return 'reject';
//
//   const result = attestationToTier(report.payload, DEFAULT_POLICY);
//   // result.tier === 'PREMIER' | 'STRONG' | 'STANDING' | 'NEW' | 'TAMPERED'
//   // result.score in [0, 1000]
//   // result.contributingFactors — breakdown for audit
// ============================================================================
// ----------------------------------------------------------------------------
// Flags that attestations may carry for partner telemetry but that must not
// force the reference tier mapping into TAMPERED. (Bureau still emits them in
// `flags` for audits.) Keep in lockstep with `verify-device.js` if extended.
// ----------------------------------------------------------------------------
export const INFORMATIONAL_ATTESTATION_FLAGS = new Set(['first_sighting']);
// ----------------------------------------------------------------------------
// DEFAULT_POLICY — mirror of the live methodology v1.1 numbers. Update this
// in lockstep with docs/methodology/GENESIS_SCORE.md and rev POLICY_VERSION.
// ----------------------------------------------------------------------------
export const DEFAULT_POLICY = {
    maxBeatRatePerMs: 1 / 25000,
    fullAgeCreditDays: 180,
    beatsLogMultiplier: 50,
    beatsScoreCap: 300,
    ageScoreCap: 300,
    baseline: 200,
    sensorBaseline: 50,
    sensorPerFieldPoints: 50,
    flaggedScoreCeiling: 199,
    tierBands: {
        PREMIER: { min: 900 },
        STRONG: { min: 750 },
        STANDING: { min: 500 },
        NEW: { min: 0 },
    },
};
/** Policy version. Bump on any change to DEFAULT_POLICY or the scoring
 *  algorithm shape. Independent from the bureau's methodology version —
 *  this is the version of the CLIENT-SIDE mapping, not the methodology
 *  the bureau used to populate the attestation's flags / bureauObserved. */
export const POLICY_VERSION = 'v2.0.2';
// ----------------------------------------------------------------------------
// attestationToTier — pure function. Same input always returns same output.
// ----------------------------------------------------------------------------
// Algorithm mirrors the live methodology v1.1, with one structural change:
// the input is a SIGNED ATTESTATION the bureau already vouched for, not raw
// proof fields. Bureau-bounded age and chain-rewind detection happened
// server-side when the attestation was minted; this function reads the
// resulting `bureauObserved` block directly. That means a partner using
// this package never has to call any bureau endpoint to re-derive a score —
// the signed attestation is sufficient input.
// ----------------------------------------------------------------------------
export function attestationToTier(attestation, policy = DEFAULT_POLICY) {
    let score = policy.baseline;
    const flags = Array.isArray(attestation.flags) ? attestation.flags : [];
    const flagged = flags.some((f) => !INFORMATIONAL_ATTESTATION_FLAGS.has(f));
    // Bureau-observed age — uses bureau clock, not node-claimed firstBeatTs.
    // The bureau has already done the bounding (firstSeenMs is the later of
    // claimed firstBeatTs and the bureau's first observation), so we trust it.
    const observedWindowMs = Math.max(0, attestation.bureauObserved.lastSeenMs - attestation.bureauObserved.firstSeenMs);
    const ageDays = observedWindowMs / 86400000;
    const bureauObservedAge = Math.min(policy.ageScoreCap, Math.max(0, Math.round((ageDays / policy.fullAgeCreditDays) * policy.ageScoreCap)));
    score += bureauObservedAge;
    // Lifetime beats — log-scale. The bureau already rate-checked this server
    // side (and would have raised `beat_rate_implausible` if the rate was
    // physically impossible), so we trust the count when no such flag is set.
    // If the flag IS present, the per-flag floor below will dominate.
    const claimedBeats = typeof attestation.chainClaim.lifetimeBeats === 'number' &&
        attestation.chainClaim.lifetimeBeats >= 0
        ? attestation.chainClaim.lifetimeBeats
        : 0;
    const lifetimeBeats = claimedBeats > 0
        ? Math.min(policy.beatsScoreCap, Math.round(Math.log10(claimedBeats + 1) * policy.beatsLogMultiplier))
        : 0;
    score += lifetimeBeats;
    // Sensor coherence — baseline + per-field bonus only when the field was
    // observed AND plausible. An unobserved field contributes 0 (not a penalty);
    // an observed-but-implausible field also contributes 0 AND triggers a
    // bureau-side flag (which the floor below will handle).
    const sc = attestation.sensorCoherence;
    let sensorCoherence = 0;
    if (sc) {
        // Only award the sensor baseline if at least one sensor was observed.
        // A device with no sensors at all shouldn't get free points just for
        // having the block present.
        const anyObserved = sc.luxObserved || sc.motionRmsObserved || sc.pressureHpaObserved;
        if (anyObserved)
            sensorCoherence += policy.sensorBaseline;
        if (sc.luxObserved && sc.luxPlausible === true) {
            sensorCoherence += policy.sensorPerFieldPoints;
        }
        if (sc.motionRmsObserved && sc.motionRmsPlausible === true) {
            sensorCoherence += policy.sensorPerFieldPoints;
        }
        if (sc.pressureHpaObserved && sc.pressureHpaPlausible === true) {
            sensorCoherence += policy.sensorPerFieldPoints;
        }
    }
    score += sensorCoherence;
    // Hard ceiling — clamp to [0, 1000] before applying the flagged floor so
    // the flagged floor (199 by default) is honored even for a node that
    // would otherwise have scored 900.
    score = Math.max(0, Math.min(1000, score));
    // Flag floor — tamper / coherence flags force TAMPERED; informational
    // flags (e.g. first_sighting) are passed through but do not flip tier.
    if (flagged) {
        score = Math.min(score, policy.flaggedScoreCeiling);
    }
    // Tier mapping.
    const tier = flagged
        ? 'TAMPERED'
        : score >= policy.tierBands.PREMIER.min
            ? 'PREMIER'
            : score >= policy.tierBands.STRONG.min
                ? 'STRONG'
                : score >= policy.tierBands.STANDING.min
                    ? 'STANDING'
                    : 'NEW';
    return {
        tier,
        score,
        flagged,
        contributingFactors: {
            baseline: policy.baseline,
            bureauObservedAge,
            lifetimeBeats,
            sensorCoherence,
        },
        flags: flags.slice(),
        policyVersion: POLICY_VERSION,
    };
}
